name: Run Gold-Nifty Bot

on:
  schedule:
    # Runs at 6 AM, 2 PM, and 10 PM IST (0:30, 8:30, and 16:30 UTC)
    - cron:  '30 0,8,16 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run bot script
      run: python bot.py
